/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package smashbrostourney;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class App {
    public App() {
        SwingUtilities.isEventDispatchThread();
        Frame f = new Frame(400, 400, "Smash Bros Bracket");
        // f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Bracket b = new Bracket(8);
        f.add(b);
        f.pack();
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }

    private static void createAndShowGUI() {
        System.out.println("Created GUI on EDT? " +
                SwingUtilities.isEventDispatchThread());
        Frame f = new Frame(400, 400, "Smash Bros Bracket");
        // f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Bracket b = new Bracket(8);
        f.add(b);
        f.pack();
    }
}
