/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package smashbrostourney;

public class App {
    public App() {
        Frame f = new Frame(400, 400, "Smash Bros Bracket");
        Panel p = new Panel(0, 0, 100, 100);
        f.add(p);
    }

    public static void main(String[] args) {
        System.out.println(new App());
    }
}
